### ISSUE TITLE
Issue with ServerSideEmit using RedisAdapter

### ISSUE THREAD

**Issue by gus3inov** [zishang520/socket.io-go-redis#1]
Hello! First off, I'd like to express my appreciation for this library. However, I've encountered an error while using `ServerSideEmit` in conjunction with the `RedisAdapter`. 

#### Code Snippet:
```go
socketIORedisClient := rtypes.NewRedisClient(ctx, redisClient.Writer())

err := socketIORedisClient.On("error", func(errors ...any) {
    slog.Error("Socket.io Redis client errors", "errors", errors)
})

if err != nil {
    slog.Error("Failed to set up Socket.io Redis client", err)
    return nil, fmt.Errorf("failed to set up Socket.io Redis client")
}

opts := socket.DefaultServerOptions()
opts.SetPath("")

socketIOAdapterBuilder := adapter.RedisAdapterBuilder{
    Redis: socketIORedisClient,
    Opts:  &adapter.RedisAdapterOptions{},
}

opts.SetAdapter(&socketIOAdapterBuilder)

server := socket.NewServer(nil, opts)

err = server.ServerSideEmit("hello", "world")
```

#### Encountered Error:
```
*json.UnsupportedTypeError=json: unsupported type: func(interface {}, error)
```
This error occurs when I attempt to use `server.ServerSideEmit("hello", "world")`. 

#### Reference:
The issue seems to be related to the code at [this point in the `socket.io-go-redis` repository](https://github.com/zishang520/socket.io-go-redis/blob/80a1232f24b25c9dd4058de08d1e7f1f5ea7da45/adapter/redis-adapter.go#L852-L854).

#### Question:
Am I using `ServerSideEmit` incorrectly, or could there be an issue with how `ServerSideEmit` interacts with `RedisAdapter`? Any guidance or suggestions on how to resolve this error would be greatly appreciated.

Thank you for your time and assistance.

**Comment by gus3inov** [comment]
I've identified that the issue originates from this line: https://github.com/zishang520/socket.io-go-redis/blob/80a1232f24b25c9dd4058de08d1e7f1f5ea7da45/adapter/redis-adapter-type.go#L47

The problem arises when attempting to marshal a function of the type func(any, error) through x.Resolve. It appears that this operation is unsupported, leading to the encountered error.

**Comment by zishang520** [comment]
Thanks for your feedback on the problem, I will improve this project when I have free time.
