### ISSUE TITLE
Request to enable new releases for repository maintenance

### ISSUE THREAD

**Issue by gus3inov** [zishang520/socket.io-go-redis#3]
Your project has been immensely beneficial to the community, and personally, it has significantly helped me.

Understanding the time and effort required to maintain such an impactful project, and knowing that your time may be limited, I'm reaching out to kindly inquire about the possibility of releasing the latest version of the repository.

I am fully aware of the constraints on your time. To assist and ensure the continued success and relevance of the repository, I'm offering my help in managing and creating new releases. If it's within the project's policies and your comfort level, could you consider granting me the necessary permissions to contribute in this way?

I completely respect your vision for the project and your decision-making process. If granting these permissions isn't feasible, I understand. However, if there's any other way I can support or contribute to the maintenance of the project, I am eager to help.

I'm looking forward to the possibility of contributing more actively in this repository.

**Comment by zishang520** [comment]
Hello, the project will continue to be maintained. I am really sorry that I
have not updated related projects for a long time. I have a new cute baby
at home and I need some time to buffer.

**Comment by gus3inov** [comment]
@zishang520 Thanks for the response and new release! Congratulations on the new addition to the family!
